CREATE TABLE IF NOT EXISTS T_EMPRESAS (
	EMP_CODG   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Empresa AAMMDDHHMMSS
    EMP_NOME   VARCHAR(80) NOT NULL, #Nome
    
    #Extensões
    EMP_MESA   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 1-Ativo
    EMP_COZI   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 1-Ativo
    EMP_ENTR   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 1-Ativo
    EMP_INTG   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 1-Ativo
    
    #Token Cardapio
    EMP_CARD   VARCHAR(5), #Codigo para vincular Cardapio
    
    #Planos
    EMP_PLNO   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Plano 0-Gratis 1-Plano1 2-Plano2
    EMP_TOKN   VARCHAR(50), #Token API
    EMP_PGMT   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 0-Não Ok 1-Atrasada 3-Pago
    PRIMARY KEY (EMP_CODG)
);
alter table T_EMPRESAS CHANGE USR_PLNO EMP_PLNO TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;
alter table T_EMPRESAS CHANGE USR_TOKN EMP_TOKN VARCHAR(50);
alter table T_EMPRESAS CHANGE USR_PGMT EMP_PGMT TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS T_FATURAS (
	FTR_CODG   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Fatura AAMMDDHHMMSS
    FTR_CODE   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Empresa AAMMDDHHMMSS
    FTR_DSCR   VARCHAR(100) NOT NULL, #Descrição da Fatura
    FTR_MNTH   INT(2) NOT NULL, #Mês Fatura
    FTR_YEAR   INT(4) NOT NULL, #Ano Fatura
    FTR_APIT   VARCHAR(200) NOT NULL, #Referencia API Pagamento
    FTR_VLRT   DECIMAL(5,2) UNSIGNED NOT NULL DEFAULT '0.00',
    FOREIGN KEY (FTR_CODE) REFERENCES T_EMPRESAS(EMP_CODG),
    PRIMARY KEY (FTR_CODG)
);

CREATE TABLE IF NOT EXISTS T_USUARIO (
	USR_CODG   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Usuario AAMMDDHHMMSS
    USR_EMAL   VARCHAR(55) NOT NULL, #Email
    USR_NOME   VARCHAR(80) NOT NULL, #Nome
    USR_IMAG   VARCHAR(200), #Imagem
    USR_NICK   VARCHAR(20) NOT NULL, #Nick name
    USR_PASS   VARCHAR(150) NOT NULL, #Senha
    USR_CNFR   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 0-Não confirmado 1-Confirmado
    USR_STTS   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0, #Status 0-OK 1-Reset Senha 3-Block
    PRIMARY KEY (USR_CODG)
);

CREATE TABLE IF NOT EXISTS T_ACESSO (
	ACC_CODE   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Empresa AAMMDDHHMMSS
    ACC_CODU   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Usuario AAMMDDHHMMSS
    ACC_NIVL   INT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT 0, #Nivel de acesso
    FOREIGN KEY (ACC_CODE) REFERENCES T_EMPRESAS(EMP_CODG),
    FOREIGN KEY (ACC_CODU) REFERENCES T_USUARIO(USR_CODG),
    PRIMARY KEY (ACC_CODE, ACC_CODU)
);

CREATE TABLE IF NOT EXISTS T_CLIENTE (
	#Chaves
    CLI_CODG   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Cliente AAMMDDHHMMSS
    CLI_CODE   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Empresa AAMMDDHHMMSS
    
    #Dados Basicos
    CLI_NOME   VARCHAR(100) NOT NULL, #Nome
    CLI_TELF   VARCHAR(20) NOT NULL, #Telefone
    
    #Endereço
    CLI_ADRS   VARCHAR(100), #Rua
    CLI_NUMB   VARCHAR(20), #Numero
    CLI_CPLT   VARCHAR(20), #Complemento
    CLI_BAIR   VARCHAR(50), #Bairro
    CLI_CITY   VARCHAR(50), #Cidade
    CLI_ESTD   VARCHAR(2), #Estado UF
    CLI_REFR   VARCHAR(50), #Ponto de Referencia
    CLI_NCEP   INT(8) UNSIGNED ZEROFILL, #CEP
    
    #Auxiliares
    CLI_PED1   TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0, #Primeiro Pedido
    CLI_FIDL   INT(8) UNSIGNED ZEROFILL NOT NULL DEFAULT 0, #Cartão fidelidade
    CLI_WALT   DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT '0.0', #Saldo
    CLI_ULTP   DATE, #Data do ultimo pedido
    
    #Acessos
    CLI_PASS   VARCHAR(150), #Senha
    CLI_STTS   TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0, #0-Sem acesso 1-Com Acesso
    CLI_KEYE   VARCHAR(50), #Codigo de entrega
    CLI_KEYM   VARCHAR(50), #Codigo de Mesa
    
    #Rate Min-0 Max-10
    CLI_RATE   TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0, #Nota do cliente, define prioridade 
    
    #Datas
    CLI_DATC   DATETIME NOT NULL, #Data de criação no sistema
    CLI_DATA   DATETIME NOT NULL, #Data de alteracao no sistema
    
    FOREIGN KEY (CLI_CODE) REFERENCES T_EMPRESAS(EMP_CODG),
    PRIMARY KEY (CLI_CODG)
);

CREATE TABLE IF NOT EXISTS T_CONFIG (
	CFG_CODE   BIGINT(12) UNSIGNED ZEROFILL NOT NULL, #Codigo Empresa AAMMDDHHMMSS
    CFG_LTCD   TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
    CFG_CEXB   TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
    FOREIGN KEY (CFG_CODE) REFERENCES T_EMPRESAS(EMP_CODG),
    PRIMARY KEY (CFG_CODE)
);